export const typography = {
  caption: 12,
  small: 13,
  body: 14,
  bodyLarge: 16,
  subtitle: 18,
  title: 22,
  display: 28,
  lineSmall: 18,
  lineBody: 21,
  lineSubtitle: 24,
  lineTitle: 28,
  lineDisplay: 34,
  weightRegular: "400" as const,
  weightMedium: "500" as const,
  weightSemibold: "600" as const,
  weightBold: "700" as const,
  weightHeavy: "800" as const,
} as const;
